> # [서론]

## numpy
- 넘파이의 주요 컨셉은 n-차원의 행렬이다.
1. 1차원 벡터
2. 2차원 벡터
3. 3차원과 그 이상

## 넘파이의 행렬과 파이썬의 배열의 차이점
- 차원이 늘어날 수 록 행렬은 배열보다 더 간편하다.
- 수직적일때, 배열보다 더 빠르다.
- 끝에 요소를 추가할 때 배열보다 느리다.
- 한개의 자료형으로 이루어졌을 때 오직 더 빠르게 작동한다.

## 1. 1차원 벡터
- 벡터의 초기설정


In [ ]:
import numpy as np

In [ ]:
a = np.array([1.,2.,3.])
a

array([1., 2., 3.])

- 행렬은 배열과 달리 끝에 요소를 추가할 때 속도가 느리기 때문에 빠른 속도를 위해서는 zeros나 empty를 통해 미리 필요한 공간을 할당하는편이 좋다.

In [ ]:
b = np.zeros(3,int)
b

array([0, 0, 0])

In [ ]:
b = np.ones(3)
b

array([1., 1., 1.])

In [ ]:
b = np.empty(3)
b

array([1., 1., 1.])

In [ ]:
b = np.full(3,7)
b

array([7, 7, 7])

- _like를 위 메소드들에게 붙여서 매개변수로 따라하고 싶은 행렬을 넣어주면 그 행렬과 같은 shape 의 행렬을 할당해준다

In [ ]:
b = np.ones_like(a)
b

array([1., 1., 1.])

- float형태의 부동소수점 배열이 필요한 경우  agrang를 통해 만들어줄 수 있다.
- 하지만 arange는 float을 처리하는데 그리 좋지는 않다.

In [ ]:
np.arange(0.4,0.8,0.1)

array([0.4, 0.5, 0.6, 0.7])

In [ ]:
np.arange(0.5,0.8,0.1)

array([0.5, 0.6, 0.7, 0.8])

- 부동소수점이 가진 단점 때문에 위 두 코드의 결과 행렬의 끝원소가 지시한 것과는 다른 결과를 도출한다.
- 하지만 이 문제를 linspace를 이용하면 된다.

In [ ]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## 벡터 인덱싱
- 행렬의 인덱싱은 views 방식으로 가져오기 때문에 원본 데이터가 수정될 수 있다.
- 행렬을 복사하고 싶다면 .copy()를 통해서 복사해야한다.

In [ ]:
a = np.array([1,2,3])
b = a        # 복사 아님 
c = a[:]      # 복사 아님
d = a.copy() # 복사