# 선형대수
[참고자료](https://codingalzi.github.io/datapy/linear_algebra_basics.html)
## 1. 벡터
- 벡터는 크기와 방향을 가지고 있는 물리값
- 순서가 존재하는 숫자의 리스트


In [3]:
# pure python
vector1 = [1,2,3]
vector2 = [4,5,6]
print(vector1, vector2)

[1, 2, 3] [4, 5, 6]


In [4]:
# numpy
import numpy as np
npVector1 = np.array([1,2,3])
npVector2 = np.array([4,5,6])
print(npVector1, npVector2)

[1 2 3] [4 5 6]


### 벡터 덧셈
- 차원이 같은 두 개의 덧셈은 같은 위치에 있는 항목끼리 더한 결과로 이루어진 벡터를 생성한다.
- (1,2) + (2,1) = (1+2, 2+1) = (3,3)

In [9]:
# pure python

from typing import List
Vector = List[float]


def vector_sum(vectors: List[Vector]) -> Vector:
    
    assert vectors                   # 1개 이상의 벡터가 주어져야 함

    num_elements = len(vectors[0])   # 벡터 개수
    
    assert all(len(v) == num_elements for v in vectors)   # 모든 벡터의 크기가 같아야 함

    # 동일한 위치의 항목을 모두 더한 값들로 이루어진 벡터 반환
    return [sum(vector[i] for vector in vectors)
            for i in range(num_elements)]

In [12]:
# pure python
vector_sum((vector1, vector2))

[5, 7, 9]

In [13]:
# numpy
npVector1+npVector2

array([5, 7, 9])

## 벡터 뺄셈
- 차원이 같은 벡터 두개의 뺄셈은 같은 위치에 있는 항목끼리 뺀 결과로 이루어진 벡터를 생성한다.
- (1,2) - (2,1) = (1-2, 2-1) = (-1, 1)

In [14]:
# pure python
def subtractV(v: Vector, w: Vector) -> Vector:
    assert len(v) == len(w)   # 두 벡터의 길이가 같아야 함

    return [v_i - w_i for v_i, w_i in zip(v, w)]

In [16]:
# pure python
subtractV(vector1, vector2)

[-3, -3, -3]

In [17]:
#numpy
npVector1-npVector2

array([-3, -3, -3])