## 넘파이 조건 설정

In [1]:
import numpy as np

In [11]:
arr = np.arange(12,0,-1) # 배열 선언
arr

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

- 단순하게 인덱스를 대괄호 안에 조건을 표현해줄 수 있다.

In [12]:
arr[arr>10]

array([12, 11])

- np.where을 통해 괄호 안에 조건을 써줄 수 있다.
- 인덱스 번호로 결과를 출력해준다.

In [13]:
np.where(arr>3)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),)

- 조건을 2개 사용하고 싶을 때는 logical_and, logical_or, logical_xor으로 조건을 2개를 넣어 줄 수도 있다.
- 이 경우에는 부울값으로 결과를 내보낸다.

In [14]:
np.logical_and(arr>3, arr%2==0)

array([ True, False,  True, False,  True, False,  True, False,  True,
       False, False, False])

- 배열의 인덱스 기능과 np.where의 출력결과를 활용하여 np.where안에 logical을 사용해주면 2개 조건을 만족시키는 배열의 요소들을 찾아낼 수 있다.

In [16]:
arr[np.where(np.logical_and(arr>3,arr%2==0))]

array([12, 10,  8,  6,  4])